title: "Bulk RNA-seq & DEA Tutorial"
description: "Tutorial for bulk RNA-seq QC, alignment, counting, DESeq2, and GSEA."

# --------------------------
# THEME
# --------------------------
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  toc_levels: "1..4"