remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  toc_levels: "1..4"

title: "Bulk RNA-seq & DEA Tutorial"
description: "Full workflow on VSC including QC, trimming, alignment, counting, DEA, and GSEA."
