remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  toc_levels: "1..4"

title: "Bulk RNA-seq & DEA Tutorial"
description: "A step-by-step bioinformatics tutorial for bulk RNA-seq and differential expression analysis (DEA) on VSC."
