title: "Bulk RNA-seq Data and Differential Expression Analysis (DEA) on VSC Clusters"
description: "Tutorial and exercises for bulk RNA-seq and differential expression analysis"
theme: jekyll-theme-primer